name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.6.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  go_router: ^14.2.7
  gap: ^3.0.1
  animated_bottom_navigation_bar: ^1.3.3
  fluttertoast: ^8.2.8
  avatar_glow: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  easy_stepper: ^0.8.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.1.0
  flutter_slidable: ^3.1.1
  lottie: ^3.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/main/
    - assets/images/welcome/
    - assets/images/service/
    - assets/json/
    - assets/lottie/
    - assets/lang/
    - .env
